### ISSUE TITLE
Datetime error running a build

### ISSUE THREAD

**Issue by gabrielfarias93** [jenkinsci/genexus-plugin#2]
Hello, i'm trying to build an application using the Genexus plugin and the console of jenkins returns the follow error:

"C:\Program Files (x86)\GeneXus\GeneXus15\teamdev.exe" history /x /utc /s:http://10.1.1.100/genexusserverxv /u:local\jenkins /p:jenkinspwd /kb:PORTAL "/from:01/01/70 0h0min0s" "/to:03/10/18 19h24min48s"
16:24:59 Error checking history:
16:24:59 Error checking history: java.nio.charset.MalformedInputException: Input length = 1
16:24:59 java.io.IOException: Error checking for last revision

scm-polling.txt file:

The value 01/01/70 0h0min0s is not valid for DateTime.

Can someone help me?

Thanks

**Comment by jlamasrios** [comment]
Hi, Gabriel

There's a problem with the time format. The plugin executes in the Jenkins context (the Java VM) and is passing a datetime parameter to the teamdev.exe (which executes in the .Net Framework context and uses the time format that was set in Windows) in a format (eg: 0h0min0s) that it can't recognize.

> The value 01/01/70 0h0min0s is not valid for DateTime.

It's probably expecting something similar to "01/01/70 00:00:00"

Do you have some plugin or tool configuration in your Jenkins installation that might be related to that non-standard time format?

**Comment by gabrielfarias93** [comment]
Hello José,

Thanks for the help, but the problem was on the region in the server where jenkins is installed, i've be changed to "en-US" and it worked, before was "pt-BR" 

Thank you!

**Comment by jlamasrios** [comment]
Excellent! 

For the record, and for anyone that may have a similar problem and happen to read this:

As fas as I know, Java takes the region / locale (and from that the formats) from the windows default, and so does the teamdev.exe. However, the defaults are user-dependent, so if the Jenkins service is started with a different user that may affect the results.

Additionally, there's a Jenkins Locale plugin (https://wiki.jenkins.io/display/JENKINS/Locale+Plugin) that let's you set a different locale (overriding the Java / Windows defaults) and that may be also a cause of this kind of problems.
