### ISSUE TITLE
Uso del plugin con Jenkins PipeLine

### ISSUE THREAD

**Issue by Lapo26** [jenkinsci/genexus-plugin#3]
Este plugin se puede utilizar con jenkins pipeline?, en caso de que si como serían las invocaciones?

**Comment by jlamasrios** [comment]
Lamentablemente aún no. Es un tema pendiente
https://issues.jenkins-ci.org/browse/JENKINS-60560

**Comment by jlamasrios** [comment]
No lo reporté en su momento aquí (disculpas) pero esto está implementado ya hace tiempo
